### ISSUE TITLE
Blender 2.90.1

### ISSUE THREAD

**Issue by ReNardier** [Songtech-0912/Prometheus-Project#2]
it has been out for a while now, are you going to make an appimage?

**Comment by Songtech-0912** [comment]
@ReNardier Yes, in fact I'll be updating stuff and finishing the docs as well very soon.

**Comment by Songtech-0912** [comment]
@ReNardier Sorry, a bit late, but I've finished making them. Download them here: <https://github.com/Songtech-0912/Prometheus-Project/releases/tag/v1.0-beta.5>
